# NUMPY

## DAY - 3

#### NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with PythonThe NumPy package is the workhorse of data analysis, machine learning, and scientific computing in the python ecosystem. Some of python’s leading package rely on NumPy as a fundamental piece of their infrastructure (examples include scikit-learn, SciPy, pandas, and tensorflow). 

In [2]:
#Importing numpy

import numpy as np

In [6]:
#numpy / array creation

# array ??  array is a data structure that stores the values that belongs to same data type
# List ?? list is a data structure in python that stores values having different datatypes.

#how array is created?/

data=np.array([1,2,3,4,5])
print(type(data))

#here we create array by initializing array elements by us.

<class 'numpy.ndarray'>


In [36]:
# there are some cases where we want NumPy to initialize the values of the array for us.
#NumPy provides methods like ones(), zeros(), and random.random() for these cases. 
#We just pass them the number of elements we want it to generate

ones=np.ones(3)
print(ones)
zeros = np.zeros(10)
print(zeros)
rand = np.random.random(10)
print(rand)




print(np.ones((3,5),dtype=int)) #defining rows and columns

[1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.92263345 0.16312147 0.20800789 0.50435156 0.71761495 0.65166763
 0.40619874 0.18204415 0.24847687 0.38715464]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [27]:
#Reshaping
np.arange(1,10).reshape(3,3)
np.arange(20).reshape(10,2)
np.arange(20).reshape(20,1)
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
#arithematic operations using numpy
data=np.array([1,2,3])
print(data)
ones=np.ones(3)
print(ones)
add = data+ones
print(add)

#subtraction
sub=data-ones
print(sub)

#multiplication
mul =data*ones
print(mul)

#division
div=data/ones
print(div)

[1 2 3]
[1. 1. 1.]
[2. 3. 4.]
[0. 1. 2.]
[1. 2. 3.]
[1. 2. 3.]


In [59]:
#copy function in Numpy
ary = np.array([1,2,3,4])
ary[1:]=100
ary


array([  1, 100, 100, 100])

In [64]:
a=np.array([1,2,3,4,5])
b=np.copy(a)
b[1:]=100
print(a)
print(b)

[1 2 3 4 5]
[  1 100 100 100 100]


In [46]:
#indexing
arr=np.array([1,2,3,4,5,6,7,8]).reshape(4,2)
print(arr)
print(arr[0])
print(arr[1:,0:])
print(arr[:,:])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2]
[[3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
array = np.array([1,2,3,4,5])
array[2:] = 100
print(array)

[  1   2 100 100 100]


In [50]:
#random distributions
np.random.rand(13,3)
#print elements between 0 to 1

array([[0.61112465, 0.75744667, 0.00784581],
       [0.86869646, 0.20965746, 0.42754879],
       [0.71645332, 0.8521213 , 0.05283865],
       [0.99224888, 0.80843107, 0.48416845],
       [0.64079816, 0.39620299, 0.55599429],
       [0.28917396, 0.15386564, 0.49744886],
       [0.48335204, 0.34249693, 0.22579337],
       [0.09619588, 0.70673928, 0.85111798],
       [0.24198864, 0.21416296, 0.89234   ],
       [0.29925805, 0.20119491, 0.47848167],
       [0.60212652, 0.44734018, 0.39101344],
       [0.30983413, 0.80891117, 0.52518912],
       [0.89049077, 0.05603878, 0.97544582]])

In [51]:
np.random.randn(4,10)
#print standard distribution

array([[-1.30888495e-01,  9.75667996e-02, -2.30427283e-01,
        -2.05978962e+00, -1.14684558e+00,  2.73734415e-01,
         1.41018597e+00, -1.16212316e+00, -1.10860201e+00,
        -1.02949004e-01],
       [ 7.20876313e-01, -3.34072295e-01,  9.72270845e-01,
        -1.04942737e+00,  1.37590468e+00, -1.51361435e-03,
        -4.78321738e-01,  1.35269308e+00,  1.73925925e+00,
         1.05754251e+00],
       [-6.68146996e-01,  1.90821206e+00, -3.22018248e-01,
        -1.79098790e-01,  1.64802438e-01, -5.70037246e-01,
         4.12605047e-01, -9.41243454e-01,  1.03456469e+00,
        -1.07824183e+00],
       [ 3.31829274e-01,  7.36601176e-01, -7.42808760e-01,
         7.29707729e-01, -1.03181794e-01,  1.38401383e+00,
        -2.12797780e+00, -4.31180789e-01, -8.88035715e-02,
         2.59987886e-01]])

In [54]:
np.random.randint(10,100,8).reshape(4,2)
# randomly select 8 numbers between 10 and 100 

array([[86, 28],
       [49, 39],
       [82, 50],
       [39, 47]])

In [56]:
np.random.random_sample((10,5))
#numbers between 0.0 to 1.0

array([[0.91342442, 0.99065516, 0.42309741, 0.87735919, 0.40589641],
       [0.86165456, 0.56644198, 0.5824229 , 0.51206806, 0.4645194 ],
       [0.97060016, 0.77746531, 0.74466175, 0.52434805, 0.95385359],
       [0.12293312, 0.95255524, 0.07294333, 0.47794642, 0.82698421],
       [0.37986554, 0.6677076 , 0.88281364, 0.95430863, 0.85674371],
       [0.04574451, 0.14140607, 0.50232924, 0.77120182, 0.91379526],
       [0.20483207, 0.68174805, 0.02108395, 0.15317562, 0.10942312],
       [0.05667479, 0.97107768, 0.89314819, 0.31984992, 0.6279816 ],
       [0.88596348, 0.00895265, 0.19055629, 0.32142699, 0.98097005],
       [0.65696186, 0.08066496, 0.01376602, 0.04647344, 0.91202044]])